FROM clang-9.0 as clang_base
MAINTAINER Marcin Copik <mcopik@gmail.com>
ARG NCPUS=1
ENV NCPUS=$NCPUS
ENV LLVM_VERSION=9.0.0

ENV PATH=/opt/llvm/bin/:$PATH

COPY install_libcxx.sh /

RUN deps='cmake ninja-build wget xz-utils python build-essential'\
  && apt-get update\
  && apt-get install -y ${deps}\
  && /bin/bash install_libcxx.sh ${LLVM_VERSION}

FROM ubuntu:bionic
COPY --from=0 /opt/libcxx /opt/llvm

